### ISSUE TITLE
预训练模型外链失效

### ISSUE THREAD

**Issue by lrq-Alice** [shenzaimin/CCKS2020-Event-extraction-3rd#3]
说明：chinese_roberta_wwm_large_ext_pytorch 预训练模型文件路径 code/CCKS-Cls/pretrained_model/Bert-wwm-ext/
下载链接：
http://pan.iflytek.com/#/link/9B46A0ABA70C568AAAFCD004B9A2C773
提取密码：43eH

**Comment by shenzaimin** [comment]
README里更新了百度网盘链接
