### ISSUE TITLE
CCKS-Cls文件夹缺少文件

### ISSUE THREAD

**Issue by lrq-Alice** [shenzaimin/CCKS2020-Event-extraction-3rd#5]
您好！
非常感谢您把run_bert.py上传，但您CCKS-Cls文件夹文件不全，里面缺少一些依赖文件，不知道您是不是没有把文件夹完整的上传。
例如缺少pybert.train model configs等
再次麻烦您把CCKS-Cls文件夹里面所有的代码上传，十分感谢！您的帮助对我的意义很大~

**Comment by shenzaimin** [comment]
所有代码已更新
